/** @type {import('next').NextConfig} */
const nextConfig = {
  // react-markdown と関連ライブラリをトランスパイル対象に追加
  transpilePackages: [
    'react-markdown',
    'react-syntax-highlighter',
    'remark-gfm',
    'unified',
    // 以下は unified や remark-gfm が依存する可能性のあるライブラリ (必要に応じて追加/削除)
    'bail',
    'ccount',
    'character-entities',
    'comma-separated-tokens',
    'decode-named-character-reference',
    'hast-util-parse-selector',
    'hast-util-whitespace',
    'is-plain-obj',
    'longest-streak',
    'markdown-table',
    'mdast-util-find-and-replace',
    'mdast-util-from-markdown',
    'mdast-util-gfm',
    'mdast-util-gfm-autolink-literal',
    'mdast-util-gfm-footnote',
    'mdast-util-gfm-strikethrough',
    'mdast-util-gfm-table',
    'mdast-util-gfm-task-list-item',
    'mdast-util-phrasing',
    'mdast-util-to-hast',
    'mdast-util-to-markdown',
    'mdast-util-to-string',
    'micromark',
    'micromark-core-commonmark',
    'micromark-extension-gfm',
    'micromark-extension-gfm-autolink-literal',
    'micromark-extension-gfm-footnote',
    'micromark-extension-gfm-strikethrough',
    'micromark-extension-gfm-table',
    'micromark-extension-gfm-tagfilter',
    'micromark-extension-gfm-task-list-item',
    'micromark-factory-destination',
    'micromark-factory-label',
    'micromark-factory-space',
    'micromark-factory-title',
    'micromark-factory-whitespace',
    'micromark-util-character',
    'micromark-util-chunked',
    'micromark-util-classify-character',
    'micromark-util-combine-extensions',
    'micromark-util-decode-numeric-character-reference',
    'micromark-util-decode-string',
    'micromark-util-encode',
    'micromark-util-html-tag-name',
    'micromark-util-normalize-identifier',
    'micromark-util-resolve-all',
    'micromark-util-sanitize-uri',
    'micromark-util-subtokenize',
    'property-information',
    'remark-parse',
    'remark-rehype',
    'space-separated-tokens',
    'trim-lines',
    'trough',
    'unist-builder',
    'unist-util-generated',
    'unist-util-is',
    'unist-util-position',
    'unist-util-stringify-position',
    'unist-util-visit',
    'unist-util-visit-parents',
    'vfile',
    'vfile-message',
    'web-namespaces',
    'xtend',
    // react-syntax-highlighter の依存関係 (必要に応じて)
    'refractor',
    'lowlight',
    'hast-to-hyperscript',
    'hastscript',
    // 'comma-separated-tokens', // 重複
    // 'property-information', // 重複
    // 'space-separated-tokens', // 重複
    'style-to-object',
  ],
};

export default nextConfig;
