linters:
  enable:
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - errcheck
    - gocritic
    - gosec
    - revive

run:
  deadline: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true