-- CreateTable
CREATE TABLE "ProofSession" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "secretHash" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "ProofLog" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "sessionId" INTEGER NOT NULL,
    "challenge" TEXT NOT NULL,
    "response" TEXT NOT NULL,
    "isSuccess" BOOLEAN NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProofLog_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "ProofSession" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
