.PHONY: play_tetris play_slippery play_invaders play_pong
play_tetris:
	go run ./cmd/chip8_ebiten/main.go -rom roms/tetris.ch8 -cycles 60

play_slippery:
	go run ./cmd/chip8_ebiten/main.go -rom roms/slipperyslope.ch8 -cycles 60

play_invaders:
	go run ./cmd/chip8_ebiten/main.go -rom roms/invaders.ch8 -cycles 60

play_pong:
	go run ./cmd/chip8_ebiten/main.go -rom roms/pong.ch8 -cycles 60
