// Code generated by ogen, DO NOT EDIT.
package api

type APISessionGetRes interface {
	aPISessionGetRes()
}

type APISessionPostRes interface {
	aPISessionPostRes()
}

type APITodosIDDeleteRes interface {
	aPITodosIDDeleteRes()
}

type APITodosIDPutRes interface {
	aPITodosIDPutRes()
}

type APITodosIDRestorePutRes interface {
	aPITodosIDRestorePutRes()
}

type APITodosPostRes interface {
	aPITodosPostRes()
}

type APITodosSortPutRes interface {
	aPITodosSortPutRes()
}
