// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APISessionGet implements GET /api/session operation.
//
// 現在のセッション情報取得.
//
// GET /api/session
func (UnimplementedHandler) APISessionGet(ctx context.Context) (r APISessionGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APISessionPost implements POST /api/session operation.
//
// セッション作成（ユーザー選択）.
//
// POST /api/session
func (UnimplementedHandler) APISessionPost(ctx context.Context, req *APISessionPostReq) (r APISessionPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosArchivedGet implements GET /api/todos/archived operation.
//
// アーカイブされたTodo一覧取得.
//
// GET /api/todos/archived
func (UnimplementedHandler) APITodosArchivedGet(ctx context.Context, params APITodosArchivedGetParams) (r *TodoList, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosGet implements GET /api/todos operation.
//
// Todo一覧取得.
//
// GET /api/todos
func (UnimplementedHandler) APITodosGet(ctx context.Context, params APITodosGetParams) (r *TodoList, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosIDDelete implements DELETE /api/todos/{id} operation.
//
// Todoアーカイブ.
//
// DELETE /api/todos/{id}
func (UnimplementedHandler) APITodosIDDelete(ctx context.Context, params APITodosIDDeleteParams) (r APITodosIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosIDPut implements PUT /api/todos/{id} operation.
//
// Todo更新.
//
// PUT /api/todos/{id}
func (UnimplementedHandler) APITodosIDPut(ctx context.Context, req *APITodosIDPutReq, params APITodosIDPutParams) (r APITodosIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosIDRestorePut implements PUT /api/todos/{id}/restore operation.
//
// アーカイブされたTodoの復活.
//
// PUT /api/todos/{id}/restore
func (UnimplementedHandler) APITodosIDRestorePut(ctx context.Context, params APITodosIDRestorePutParams) (r APITodosIDRestorePutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosPost implements POST /api/todos operation.
//
// Todo新規作成.
//
// POST /api/todos
func (UnimplementedHandler) APITodosPost(ctx context.Context, req *APITodosPostReq) (r APITodosPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APITodosSortPut implements PUT /api/todos/sort operation.
//
// Todoの並び順一括更新.
//
// PUT /api/todos/sort
func (UnimplementedHandler) APITodosSortPut(ctx context.Context, req *APITodosSortPutReq) (r APITodosSortPutRes, _ error) {
	return r, ht.ErrNotImplemented
}
