// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	APISessionGetOperation        OperationName = "APISessionGet"
	APISessionPostOperation       OperationName = "APISessionPost"
	APITodosArchivedGetOperation  OperationName = "APITodosArchivedGet"
	APITodosGetOperation          OperationName = "APITodosGet"
	APITodosIDDeleteOperation     OperationName = "APITodosIDDelete"
	APITodosIDPutOperation        OperationName = "APITodosIDPut"
	APITodosIDRestorePutOperation OperationName = "APITodosIDRestorePut"
	APITodosPostOperation         OperationName = "APITodosPost"
	APITodosSortPutOperation      OperationName = "APITodosSortPut"
)
