apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
    version: 1
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: |-
            "trace_id":"(?P<traceID_val>[0-9a-fA-F]{32})"
          name: "Trace (from slog)"
          url: "${traceID_val}"
    version: 1
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogs:
        datasourceUid: "loki"
        tags: ["job", "instance", "pod", "namespace", "container", "host"]
        mappedTags: [{ key: "service.name", value: "app" }]
        spanStartTimeShift: "1s"
        spanEndTimeShift: "1s"
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: "prometheus"
      search:
        hide: false
      nodeGraph:
        enabled: true
    version: 1
    editable: true
