global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "go_services"
    static_configs:
      - targets:
          - "host.docker.internal:8080" # gateway_service
          - "host.docker.internal:8081" # product_service
          - "host.docker.internal:8082" # inventory_service
          - "host.docker.internal:8083" # order_service

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
