version: "3"

vars:
  GO_MODULE: github.com/lirlia/100day_challenge_backend

tasks:
  default:
    cmds:
      - go tool task --list-all

  build:
    cmds:
      - go build -o bin/server ./server

  dev:
    cmds:
      - go tool air

  docker-compose:
    cmds:
      - docker-compose up -d

  generate:
    cmds:
      - ogen generate --package api --target api --clean api/openapi.yaml
      - go generate ./...

  test:
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run ./...
