// Code generated by ogen, DO NOT EDIT.

package handler

// OperationName is the ogen operation name
type OperationName = string

const (
	ArchiveTodoOperation      OperationName = "ArchiveTodo"
	CreateTodoOperation       OperationName = "CreateTodo"
	GetArchivedTodosOperation OperationName = "GetArchivedTodos"
	GetTodosOperation         OperationName = "GetTodos"
	GetUsersOperation         OperationName = "GetUsers"
	SetSessionOperation       OperationName = "SetSession"
	UnarchiveTodoOperation    OperationName = "UnarchiveTodo"
	UpdateTodoOperation       OperationName = "UpdateTodo"
	UpdateTodoOrderOperation  OperationName = "UpdateTodoOrder"
	UpdateTodoStatusOperation OperationName = "UpdateTodoStatus"
)
