// Code generated by ogen, DO NOT EDIT.

package handler

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ArchiveTodo implements archiveTodo operation.
//
// Archive a ToDo.
//
// DELETE /todos/{todoId}
func (UnimplementedHandler) ArchiveTodo(ctx context.Context, params ArchiveTodoParams) error {
	return ht.ErrNotImplemented
}

// CreateTodo implements createTodo operation.
//
// Create a new ToDo.
//
// POST /todos
func (UnimplementedHandler) CreateTodo(ctx context.Context, req *CreateTodoRequest) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetArchivedTodos implements getArchivedTodos operation.
//
// Get list of archived ToDos for the current user.
//
// GET /todos/archived
func (UnimplementedHandler) GetArchivedTodos(ctx context.Context, params GetArchivedTodosParams) (r []Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTodos implements getTodos operation.
//
// Get list of ToDos for the current user.
//
// GET /todos
func (UnimplementedHandler) GetTodos(ctx context.Context, params GetTodosParams) (r []Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// Get list of users.
//
// GET /users
func (UnimplementedHandler) GetUsers(ctx context.Context) (r []User, _ error) {
	return r, ht.ErrNotImplemented
}

// SetSession implements setSession operation.
//
// Set current user session.
//
// POST /session
func (UnimplementedHandler) SetSession(ctx context.Context, req *SetSessionRequest) error {
	return ht.ErrNotImplemented
}

// UnarchiveTodo implements unarchiveTodo operation.
//
// Unarchive a ToDo.
//
// PATCH /todos/{todoId}/unarchive
func (UnimplementedHandler) UnarchiveTodo(ctx context.Context, params UnarchiveTodoParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTodo implements updateTodo operation.
//
// Update an existing ToDo.
//
// PUT /todos/{todoId}
func (UnimplementedHandler) UpdateTodo(ctx context.Context, req *UpdateTodoRequest, params UpdateTodoParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTodoOrder implements updateTodoOrder operation.
//
// Update the sort order of multiple ToDos.
//
// PATCH /todos/order
func (UnimplementedHandler) UpdateTodoOrder(ctx context.Context, req *UpdateTodoOrderRequest) error {
	return ht.ErrNotImplemented
}

// UpdateTodoStatus implements updateTodoStatus operation.
//
// Update the status of a ToDo.
//
// PATCH /todos/{todoId}/status
func (UnimplementedHandler) UpdateTodoStatus(ctx context.Context, req *UpdateTodoStatusRequest, params UpdateTodoStatusParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
