import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getAllUsers } from "./_lib/users"; // サーバーサイドで全ユーザー取得
import AppLayout from "./AppLayout"; // クライアントコンポーネントのレイアウト
import { CurrentUserProvider } from "@/context/CurrentUserContext"; // Provider をインポート

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Day 3: Match App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const users = await getAllUsers(); // サーバーコンポーネントでデータ取得

  return (
    <html lang="ja">
      <body className={inter.className}>
        <CurrentUserProvider>
          <AppLayout users={users}>
            {children}
          </AppLayout>
        </CurrentUserProvider>
      </body>
    </html>
  );
}
