// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User ãƒ¦ãƒ¼ã‚¶ãƒ¼
type User struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:ãƒ¦ãƒ¼ã‚¶ãƒ¼ID" json:"id"`                   // ãƒ¦ãƒ¼ã‚¶ãƒ¼ID
	Name      string     `gorm:"column:name;type:varchar(255);not null;uniqueIndex:name,priority:1;comment:ãƒ¦ãƒ¼ã‚¶ãƒ¼å" json:"name"` // ãƒ¦ãƒ¼ã‚¶ãƒ¼å
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:ä½œæˆæ—¥æ™‚" json:"created_at"`      // ä½œæˆæ—¥æ™‚
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
